name: "Create S3"
run-name: "Create S3"

on:
  push:
    branches: [ "main" ]
jobs:

  build-create-s3:
    runs-on: ubuntu-lastest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          token: ${{ secrets.TOKEN_GITHUB }}
          aws-region: ${{ secrets.REGION }}

      - name: Create Dir to S3 -source
        run: aws s3api create-bucket --bucket ${{ vars.AWS_BUCKET }} | grep -w ${{ vars.AWS_BUCKET }} >/dev/null
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        